//  use this quizData in your app.
import { v4 as uuidv4 } from "uuid";

export const quizData = [
  {
    id: uuidv4(),
    question: "Which language runs in a web browser?",
    a: "Java",
    b: "C",
    c: "Python",
    d: "JavaScript",
    correct: "d",
  },
  {
    id: uuidv4(),
    question: "What does CSS stand for?",
    a: "Central Style Sheets",
    b: "Cascading Style Sheets",
    c: "Cascading Simple Sheets",
    d: "Cars SUVs Sailboats",
    correct: "b",
  },
//   {
//     id: uuidv4(),
//     question: "What does HTML stand for?",
//     a: "Hypertext Markup Language",
//     b: "Hypertext Markdown Language",
//     c: "Hyperloop Machine Language",
//     d: "Helicopters Terminals Motorboats Lamborginis",
//     correct: "a",
//   },
//   {
//     id: uuidv4(),
//     question: "What year was JavaScript launched?",
//     a: "1996",
//     b: "1995",
//     c: "1994",
//     d: "none of the above",
//     correct: "b",
//   },
//   {
//     id: uuidv4(),
//     question: "What is the capital of France?",
//     a: "Berlin",
//     b: "Madrid",
//     c: "Paris",
//     d: "Lisbon",
//     correct: "c",
//   },
//   {
//     id: uuidv4(),
//     question: "Which planet is known as the Red Planet?",
//     a: "Earth",
//     b: "Mars",
//     c: "Jupiter",
//     d: "Saturn",
//     correct: "b",
//   },
//   {
//     id: uuidv4(),
//     question: "What is the largest ocean on Earth?",
//     a: "Atlantic Ocean",
//     b: "Indian Ocean",
//     c: "Arctic Ocean",
//     d: "Pacific Ocean",
//     correct: "d",
//   },
//   {
//     id: uuidv4(),
//     question: "Who wrote 'To Kill a Mockingbird'?",
//     a: "Harper Lee",
//     b: "J.K. Rowling",
//     c: "George Orwell",
//     d: "Jane Austen",
//     correct: "a",
//   },
//   {
//     id: uuidv4(),
//     question: "What is the chemical symbol for water?",
//     a: "H2O",
//     b: "CO2",
//     c: "O2",
//     d: "H2",
//     correct: "a",
//   },
//   {
//     id: uuidv4(),
//     question: "Who painted the Mona Lisa?",
//     a: "Vincent van Gogh",
//     b: "Leonardo da Vinci",
//     c: "Pablo Picasso",
//     d: "Claude Monet",
//     correct: "b",
//   },
//   {
//     id: uuidv4(),
//     question: "What is the smallest unit of life?",
//     a: "Atom",
//     b: "Cell",
//     c: "Molecule",
//     d: "Tissue",
//     correct: "b",
//   },
//   {
//     id: uuidv4(),
//     question: "What is the hardest natural substance on Earth?",
//     a: "Gold",
//     b: "Iron",
//     c: "Diamond",
//     d: "Platinum",
//     correct: "c",
//   },
//   {
//     id: uuidv4(),
//     question:
//       "Which element is necessary for the process of photosynthesis?",
//     a: "Carbon Dioxide",
//     b: "Oxygen",
//     c: "Nitrogen",
//     d: "Hydrogen",
//     correct: "a",
//   },
//   {
//     id: uuidv4(),
//     question: "What is the currency of Japan?",
//     a: "Yuan",
//     b: "Won",
//     c: "Yen",
//     d: "Dollar",
//     correct: "c",
//   },
];
